Matematica = input ("Digite  a nota bimestral: ")
Portugues = input ("Digite a nota bimestral: ")
Quimica = input ("Digite a nota bimestral: ")
Fisica = input ("Digite a nota bimestral: ")
Matematica = float (Matematica)
Portugues = float (Portugues)
Quimica = float (Quimica)
Fisica = float (Fisica)
MediaGeral = ((Matematica + Portugues + Quimica + Fisica) / 4)
print ("A média Geral é: ",MediaGeral)
